---
title: "R Notebook - Flipping MetaboScape outputs to 'tidy format'"
author: "Nathan Lawler"
output: html_notebook
  github_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
    df_print: paged
always_allow_html: true
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
```

#The following notebook will be used to transform the output from MetaboScape into a usable dataframe (i.e. annotation and data matrix)

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(openxlsx)
library(svDialogs)
library(here)
```


#If you have the Datasets as your sys enviro then you can navigate using the path below.
```{r, Select file to be read.}

dlg_message("Please select your metaboscape workbook"); pathToData <- file.choose()

```

# Setup Configuation file and read annotations config file
# This list will ne expanded as ANPC take on more cohorts

```{r, User input required here for which cohort is required for reading in}
pathwest <- 0
biogune <- 1
cambridge <- 0
harvard <- 0
```

```{r warning=TRUE, error=TRUE}

mscapeData <- read.table(pathToData,
                                  sep = ",",
                                  header = FALSE,
                                  check.names = FALSE)
```

```{r load annotations pathwest, echo=FALSE, warning=FALSE, include=FALSE}
get_annotations_wa <- function() {
  pathToData <- file.path(Sys.getenv()['DATASETS'], "covid19")
  load(file.path(pathToData, "pathwest", "dataElements", "covid19_pathwest_ANN.daE"))
  annPath = annotations@obsDescr[[1]]
  annPath = annPath[,c(1,4,12)]
  colnames(annPath) = c("sampleID", "class", "tpoint")
  
  load(file.path(pathToData, "pathwestFollowUp", "dataElements","covid19_pathwestFU_ANN_recovery.daE"))
  annPathFU = annotations@obsDescr[[1]]
  annPathFU = annPathFU[,c(1,2,14)]
  colnames(annPathFU) = c("sampleID", "class","tpoint")
  annPathFU$class = "rec"
  annPathFU$tpoint = "rec"
  load(file.path(pathToData, "healthyBank", "DataElements","covid19_HTYBK_PLA_ANN_recovery.daE"))
  annPathHB = annotations@obsDescr[[1]]
  annPathHB = annPathHB[,1:3]
  colnames(annPathHB) = c("sampleID", "class","tpoint")
  annPathHB$class = "hty"
  annPathHB$tpoint = "hty"
  annWA = rbind(annPath,annPathFU,annPathHB)
  annWA$sampleID[annWA$sampleID == "COV0120"] <- "COV01200"
  return(annWA)
}
```

```{r load annotations bioGUNE, echo=FALSE, warning=FALSE, include=FALSE}
get_annotations_biogune <- function() {
  pathToData <- file.path(Sys.getenv()['DATASETS'], "covid19")
  load(file.path(pathToData,"bioGune","DataElements", 'covid19_bioGune_PLA_ANN.daE'))
  annBioGune = covid19_bioGune_PLA_ANN@obsDescr[[1]]
  return(annBioGune)
}
```

```{r Break up data to create a datasheet and an annotations sheet}
v <- data.frame(t(mscapeData[1:3,]))
v <- v[-c(1:3),]
v$Idx <- (1:nrow(v)) 
v <- v %>% relocate(Idx, .before = everything())
colnames(v) <- c("Idx", "m/z", "Name", "Formula") 

#Remove rows from data set and set new headers
ds <- mscapeData[4:nrow(mscapeData),]

prefix <- "M"
suffix <- seq(ds[,4:ncol(ds)])
my.names <- paste(prefix, suffix, sep = "")

colnames(ds) <- c("Filename",
                  "Batch",
                  "SampleType", my.names)

ds$Idx <- 1:nrow(ds)
ds <- ds %>% relocate(Idx, .before = everything())

#Insert QC column using logical

ds$QC <- ifelse(ds$SampleType == "PQC", 1,0)
ds <- ds %>% relocate(QC, .after = SampleType)

# Insert SampleID

ds$SampleID <- sapply(strsplit(as.character(ds$Filename),"_"),"[",8)
ds <- ds %>% relocate(SampleID, .after = SampleType)


#Insert label names in Peak dataframe
v$label <- (my.names)

```

```{r}

if(pathwest == 1){
  ann <- get_annotations_wa()
}

if(biogune == 1){
  ann <- get_annotations_biogune()  
}  

if(cambridge == 1){
  ann <- get_annotations_cambridge()
}

# ds <- ds[which(ds$SampleID %in% ann$sampleID),]


```

```{r}

ann2<- ann[match(ds$SampleID, ann$sampleID),]

ds$class <- ann2$group
ds$severity <- ann2$category_bergamaschi
ds <- ds %>% relocate(class, .after = QC)
ds <- ds %>% relocate(severity, .after = class)
ds$class[is.na(ds$class)] <-  NaN
ds$severity[is.na(ds$severity)] <- NaN

ds$class <- ifelse(ds$class == "NaN", paste0(ds$SampleType), paste0(ds$class))
# ds$class <- ann2$group[match(ds$SampleID,ann2$sampleID),]


```

```{r}

projectTitle <- "AddTitleHERE.xlsx"

wb <- createWorkbook(projectTitle)
addWorksheet(wb, "Data")
addWorksheet(wb, "Peak")

writeData(wb, "Data", ds, colNames = TRUE)
writeData(wb, "Peak", v, colNames = TRUE)

pathToSave <- rstudioapi::selectDirectory()
pathToSave <- file.path(pathToSave, projectTitle)

saveWorkbook(wb, file = pathToSave, overwrite = TRUE)

cat(crayon::blue('DONE! Files saved as work sheets - Data & Peak'))
```
