---
title: "R Notebook"
output: html_notebook
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following notebook will parse through the output saved from the "Flip_Metaboscape" notebook.

```{r}
library(readxl)
library(tidyverse)
library(reshape)
library(plotly)
```
User to define options
```{r}
projectTitle <- "AddTitleHere.xlsx"

dlg_message("Please select your metaboscape workbook"); pathToData <- file.choose()
```

```{r read in Data File}

read_excel_allsheets <- function(pathToData, tibble = TRUE) {
    # I prefer straight data.frames
    # but if you like tidyverse tibbles (the default with read_excel)
    # then just pass tibble = TRUE
    sheets <- readxl::excel_sheets(pathToData)
    x <- lapply(sheets, function(X) readxl::read_excel(pathToData, sheet = X))
      if(!tibble) x <- lapply(x, tibble_row())
    names(x) <- sheets
    x
}

mysheets <- read_excel_allsheets(pathToData)

```

USER to set parameters here
```{r configuration file}
C.QCClean = 1
C.SNRClean = 1

C.QCType = 'np' #or 'p'
C.QCval = 30

sampleClean <- "PQC" #LTR

```

```{r}
Data <- mysheets[["DataClean"]]
Meta <- Data %>% select(-starts_with("M"))
Peak <- mysheets[["PeakClean"]]
```

```{r}
X <- Data %>% select(starts_with("M"))
X[X==0] <- NaN

# QC <-Meta$QC ==1
QC <- Meta$SampleType == sampleClean 

X1qc <- as.matrix(X[QC,])
X1sample <- as.matrix(X[!QC,])

if (C.QCType == 'p'){
RSDqc <- apply(X1qc, 2, function(r){
  qcSD <- sd(as.numeric(r),na.rm = TRUE)
  qcMean <- mean(as.numeric(r), na.rm = TRUE)
  rsdLoop <- (qcSD*100)/qcMean
})
  Peak$RSD <- RSDqc 

} else if (C.QCType == "np"){

  MPAqc <- apply(X1qc, 2, function(m){
  MPAqc <- median(as.numeric(m), na.rm = TRUE)
  RSD <- 100*mad(as.numeric(m), constant = 1.4826, na.rm = TRUE)/MPAqc
})
  Peak$MADrsd <- MPAqc
}

# Peak$RSD <- RSDqc 
# Peak$MADrsd <- MPAqc

```

```{r}
if (C.QCClean == 1){
  if (C.QCType == "p"){
  val <- C.QCval
  cut <- Peak$RSD > val
  cat(crayon::red('The number of samples with more than', val,"% RSD =",sum(cut==TRUE, na.rm = TRUE)))
  fi <- which(Peak$RSD < val)
} else{ 
    val <- C.QCval
    cut <- Peak$MADrsd > val
    cat(crayon::red('The number of samples with more than', val,"% madRSD =",sum(cut==TRUE, na.rm = TRUE)))
    fi <- which(Peak$MADrsd < val)
    }
}
```

```{r}
Metabolite_List <- as.list(Peak %>% filter(MADrsd < val) %>% select(label))

DataClean <- Data %>% select(any_of(Metabolite_List[[1]]))

PeakClean <- Peak %>% filter(label %in% Metabolite_List[[1]])

DataClean <- cbind(Meta, DataClean)

```

```{r warning=FALSE}
wb <- loadWorkbook(pathToData)

addWorksheet(wb, "DataCleaned")
addWorksheet(wb, "PeakCleaned")

writeData(wb, "DataCleaned", DataClean, colNames = TRUE)
writeData(wb, "PeakCleaned", PeakClean, colNames = TRUE)

saveWorkbook(wb, file = pathToData, overwrite = TRUE)

cat(crayon::blue('DONE! Files saved as work sheets - DataCleaned & PeakCleaned'))

```

